Repository frontity/frontity, pull requests merged in 2020-04, with the labels that each got.

#321 fixes `popstate` handler when state is null for `#element`-like links
  .changeset/red-wombats-pull.md
  e2e/integration/tiny-router.spec.js
  e2e/packages/tiny-router/package.json
  e2e/packages/tiny-router/src/index.tsx
  e2e/packages/tiny-router/types.ts
  e2e/project/frontity.settings.ts
  e2e/project/package.json
  e2e/support/commands.js
  examples/mars-theme-example/package.json
  packages/tiny-router/src/actions.ts
  packages/tiny-router/types.ts
Labels: bug

#388 TwentyTwenty: Tag underline on hover doesn't work fine #372
  .changeset/polite-masks-rule.md
  packages/twentytwenty-theme/src/components/post/post-meta-item.js
Labels: contribution

#410 github-actions: Add `actions-comment-run` workflow
  .github/workflows/comment-run.yml
Labels: just testing
