Repository frontity/frontity, pull requests merged in 2020-06, with the labels that each got.

#454 Change spanish word Fecha from mars-theme
  .changeset/light-bulldogs-love.md
  packages/mars-theme/src/components/post.js
Labels: contribution

#456 Replace `lodash-es` by `lodash`
  .changeset/big-pugs-pump.md
  packages/core/package.json
  packages/core/src/config/babel/__tests__/__snapshots__/index.ts.snap
  packages/core/src/config/babel/index.ts
  packages/core/src/config/webpack/__tests__/__snapshots__/index.ts.snap
  packages/core/src/config/webpack/resolve.ts
Labels: bug, priority: high

#471 Fix analytics component
  .changeset/great-lobsters-bow.md
  e2e/integration/analytics.spec.js
  e2e/packages/analytics/src/index.tsx
  e2e/packages/analytics/types.ts
  e2e/project/frontity.settings.ts
  e2e/project/package.json
  packages/analytics/package.json
  packages/analytics/src/components/index.tsx
  packages/analytics/types.ts
  packages/google-analytics/types.ts
Labels: bug

#503 Fix when prop child switch
  .changeset/polite-ladybugs-relax.md
  packages/components/__tests__/switch.tests.tsx
  packages/components/switch.tsx
Labels: contribution
